### ISSUE TITLE
Numeric columns are sorted as text

### ISSUE THREAD

**Issue by PhilJollans** [cyb3rm4ge/IEnumerableVisualizer#1]
If you sort the table on a numeric column, the values are sorted as text, instead of sorting them numerically.

Thus 1312 is sorted by 370.

![image](https://user-images.githubusercontent.com/5785223/76206366-2b0ac380-61fc-11ea-8496-7d79200542c3.png)

**Comment by cyb3rm4ge** [comment]
This has been resolved and published in version 2.1.5.
Values now retain their type unless they throw property errors.
