### ISSUE TITLE
Support for HashSet?

### ISSUE THREAD

**Issue by LaraSQP** [cyb3rm4ge/IEnumerableVisualizer#3]
It would be most appreciated if you could support `HashSets`.

Also, you mention in the  Visual Studio Marketplace that you have:

> Updated Overview with instructions and screenshot that has a green arrow pointing to the magnifying glass icon

I cannot find the overview or the screenshot.

Thank you very much. Great extension (if I can get to use it).

**Comment by cyb3rm4ge** [comment]
Resolved in version 2.7.2. Re-added a preview image.

![Preview](https://user-images.githubusercontent.com/12520844/80550778-03bbb180-8976-11ea-9a8b-dc066028626b.png)

**Comment by LaraSQP** [comment]
That's just fantastic.

Just tested it. You rock, man.

I now I am pushing my luck here but, is there a way your extension could use the same font as the editor's?

**Comment by cyb3rm4ge** [comment]
Sure, I will do some research and put the request in the backlog. Thank you.
